CREATE DATABASE IF NOT EXISTS dumbassia;
USE dumbassia;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  nickname VARCHAR(255) DEFAULT NULL,
  roast_summary TEXT DEFAULT NULL,
  avatar_traits JSON DEFAULT NULL,
  self_esteem INT NOT NULL DEFAULT 100,
  roast_count INT NOT NULL DEFAULT 0,
  game_score INT NOT NULL DEFAULT 0,
  stupidity_score INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quiz_answers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  question VARCHAR(255) NOT NULL,
  answer VARCHAR(255) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
